exports.WEB_ADMIN = "WEB_ADMIN";
exports.USER = "USER";
exports.TRAINER = "TRAINER";
exports.ADMIN = "ADMIN";
exports.TRANSFER_LICENSE_CONDITIONS = "TRANSFER_LICENSE_CONDITIONS";
exports.TRANSFER_LICENSE_ALLOWED_TIMES = "TRANSFER_LICENSE_ALLOWED_TIMES";
exports.TRANSFER_LICENSE_MAX_COMPLETION_PERCENTAGE =
  "TRANSFER_LICENSE_MAX_COMPLETION_PERCENTAGE";
exports.TRANSFER_LICENSE_MAX_TIME_IN_DAYS = "TRANSFER_LICENSE_MAX_TIME_IN_DAYS";
exports.GAME_RESET_AVAILABLE_MAX_LEVEL = "GAME_RESET_AVAILABLE_MAX_LEVEL";
exports.PAYMENT_INITIATED = "PAYMENT_INITIATED";
exports.PAYMENT_FAILED = "PAYMENT_FAILED";
exports.PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
